[package]
name = "distance"
version = "0.1.0"
edition = "2021"

[[test]]
name = "distance"
path = "src/main.rs"

    [test.env]
    RUST_BACKTRACE=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
